### ISSUE TITLE
Customize the Jenkins logo

### ISSUE THREAD

**Issue by dbsanfte** [jenkinsci/material-theme-plugin#38]
### What feature do you want to see added?

Is there a way to customize the logo in the top left? If not, this would be a nice feature. Would rather not have to resort to css hacking if I can avoid it :)

**Comment by timbrown5** [comment]
I would argue this would be a better placed in [Theme Manager Plugin](https://github.com/jenkinsci/theme-manager-plugin). Then all themes would benefit from the feature (and users wouldn't have to set a logo for every theme).

**Comment by maxnitze** [comment]
There is a workaround to do it right now (just to leave it here):

* additionally install the plugin `simple-theme-plugin` (https://plugins.jenkins.io/simple-theme-plugin)
* use its CSS configuration to
  * replace the Jenkins logo
    ```css
    #jenkins-home-link > img#jenkins-head-icon {
      content: url(...);
    }
    ```
  * optional: hide the "Jenkins" text
    ```css
    #jenkins-home-link > img#jenkins-name-icon {
      display: none !important;
    }
    ```
* in JCasC I have this config, for example
  ```yaml
  unclassified:
    themeManager:
      disableUserThemes: false
      theme: 'darkSystem'
    simple-theme-plugin:
      elements:
        - cssText:
            text: |-
              /* replace logo in header. will probably be added as a feature to the theme-manager plugin (https://github.com/jenkinsci/theme-manager-plugin/issues/132) */
              #jenkins-home-link > img#jenkins-head-icon {
                content: url('data:image/png;base64,<BASE64 ENCODED PNG IMAGE>');
              }
              #jenkins-home-link > img#jenkins-name-icon {
                display: none !important;
              }

  ```
