### ISSUE TITLE
Copy over the console output styles from afonsof/jenkins-material-theme

### ISSUE THREAD

**Issue by wejrox** [jenkinsci/material-theme-plugin#6]
The console within the afonsof material theme which this is based upon has some styling for the console which increases readability, most of which is set by modifying the `console-output` class as follows:
```css
.console-output {
    padding: 10px 20px;
}

.console-output, .console-output * {
    position: relative;
    font-family: Roboto Mono,monospace!important;
    font-size: 14px;
    background: #263238;
    color: #e9eded;
    cursor: text;
}
```

Some additional formatting is set elsewhere which affects the style too (not certain how/where this is set, but it's definitely by afonsof):
```css
#main-panel>pre {
    font-family: Roboto Mono,monospace!important;
}
:not(div.ace_editor) {
    font-family: Roboto,sans-serif!important;
    outline: 0;
}
```
